# Reload tmux config with `prefix r`
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Set the default terminal mode to 256color mode
set -g default-terminal "tmux-256color"

# Set delay between prefix and command
set -s escape-time 1

# Setting the prefix from C-b to C-a
set -g prefix C-a

# Free the original Ctrl-b prefix keybinding
unbind C-b

# Enable mouse
set -g mouse on

# Enable vi mode
set -g mode-keys vi

# Split panes with \ and -
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Set window indexing to start at 1 instead of 0
set -g base-index 1

# Set pane indexing to start at 1 instead of 0
setw -g pane-base-index 1

# Move between panes with Prefix h,j,k,l
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Display Popups
bind C-y display-popup \
  -d "#{pane_current_path}" \
  -w 90% \
  -h 90% \
  -E "lazygit"
bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "zsh"

# Status bar
set -g status-right-length 65
set -g status-right '#{battery_icon_charge}  #{battery_percentage}#{battery_icon_status}#{battery_remain} | CPU:#{cpu_percentage} | RAM: #{ram_percentage} | %a %d/%m/%y %H:%M '
# setw -g window-status-format "#[fg=$color_gray,italics]#I: #[noitalics]#W"
# setw -g window-status-current-format "#[fg=$color_purple,italics]#I: #[fg=$color_buffer,noitalics,bold]#W"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-battery'
set -g @plugin 'wfxr/tmux-fzf-url'

# tmux-battery
set -g @batt_icon_charge_tier8 ""
set -g @batt_icon_charge_tier7 ""
set -g @batt_icon_charge_tier6 ""
set -g @batt_icon_charge_tier5 ""
set -g @batt_icon_charge_tier4 ""
set -g @batt_icon_charge_tier3 ""
set -g @batt_icon_charge_tier2 ""
set -g @batt_icon_charge_tier1 ""
set -g @batt_icon_status_charged " "
set -g @batt_icon_status_charging "  "
set -g @batt_icon_status_discharging " "
set -g @batt_icon_status_attached " "
set -g @batt_icon_status_unknown " "
set -g @batt_remain_short true

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
